
project_id = "vwtracpgzdqrowvjmizi"

[functions.analyze-website.deployment]
allowed_import_urls = ["https://esm.sh/*"]

[functions.analyze-website.import_map]
imports = { "openai" = "https://esm.sh/openai@4.20.1" }
