
project_id = "vwtracpgzdqrowvjmizi"

[functions.analyze-website.deployment]
allowed_import_urls = ["https://esm.sh/*", "https://deno.land/std@0.168.0/http/server.ts", "https://deno.land/x/xhr@0.1.0/mod.ts"]

[functions.analyze-website.import_map]
imports = { "openai" = "https://esm.sh/openai@4.20.1" }

[functions.send-email.deployment]
allowed_import_urls = ["https://deno.land/std@0.168.0/http/server.ts"]
