
project_id = "vwtracpgzdqrowvjmizi"

[functions.analyze-website]
verify_jwt = false
allowed_import_urls = ["https://esm.sh/*", "https://deno.land/std@0.168.0/http/server.ts", "https://deno.land/x/xhr@0.1.0/mod.ts"]
import_map_path = "supabase/functions/analyze-website/import_map.json"

[functions.send-email]
verify_jwt = false
allowed_import_urls = ["https://deno.land/std@0.168.0/http/server.ts"]
