
project_id = "vwtracpgzdqrowvjmizi"

[functions.analyze-website]
verify_jwt = false
import_map = "functions/analyze-website/import_map.json"

[functions.send-email]
verify_jwt = false

[functions.seo-analysis]
verify_jwt = false

[functions.seo-task-manager]
verify_jwt = false
