
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwtracpgzdqrowvjmizi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3dHJhY3BnemRxcm93dmptaXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDA4ODIsImV4cCI6MjA1OTA3Njg4Mn0.WC6DrG_ftze64gQVajR-n1vjfjMqA_ADP_hyTShQckA";

// Determine if in production environment
const isProd = typeof window !== 'undefined' && 
              (window.location.hostname === 'seoaudit.pt' || 
               window.location.hostname.includes('suite.seoaudit.pt'));

// Configure redirect URL based on environment
const redirectUrl = isProd 
  ? 'https://seoaudit.pt/reset-password' 
  : `${window.location.origin}/reset-password`;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Add redirectTo directly to auth functions when needed, not in client config
